[package]
name = "my_rust_contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-sdk = "4.0.0"
borsh = "0.9"
serde = "1.0"
serde_json = "1.0"
